### ISSUE TITLE
Decide license for project

### ISSUE THREAD

**Issue by blujan** [PortlandAssembly/The-project#1]
Aside from the the regular GPL, at the core of the issue is:

- Do we want to restrict who can charge for use or sell of this software (as the GPL is permissive on this point)

- Will this have an potential impact on PA or similar groups?

**Comment by goldenapples** [comment]
I've read through the [Peer Production License](https://wiki.p2pfoundation.net/Peer_Production_License) and the theory behind it, in the Tele-kommunist Manifesto and a little bit of online debate. I really like the thinking behind it - I'd actually like to do some more discussion around the Telekommunist Manifesto at some point, because there are ideas in there I'd like to explore in more depth.

I don't see how any of this would affect Portland Assembly of any other group that might make use of the tool. Basically, the PPL license states that worker-owned collectives where all profits are distributed equally among the worker-owners can charge for use of the product, and no other organization can. 

I don't think the PPL was written with software tools in mind at all - it seems much more geared toward creative works like music, art, or plays. I can't think of any case where a for-profit group would be using our software and charging for its use - at best, it's a tool that could enable existing organizations to do their work better, and while that organization might be collecting dues from its members or supporters, it wouldn't be a case where they'd be charging for the ability to be part of a rapid response network. So I can't see how those terms of the license would be enforceable.

That said, I support switching from GPL to PPL to signal support for copyfarleft ideas. But its a minor issue to me.

**Comment by blujan** [comment]
I think the sense that it's meant more for media work is at least in part due to the fact that it's based on the Creative Commons license, which is [specifically against using it for software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).

That said, I don't see any issues with it either.
