### ISSUE TITLE
Zero Knowledge database 

### ISSUE THREAD

**Issue by ssiekmann** [PortlandAssembly/The-project#8]
If we offer hosted solution, do we implement a zero knowledge database layer to protect against malicious database administrators and evil actors. 

Possible solutions:

https://docs.zerodb.com

https://gist.github.com/thiloplanz/e1136a04b26c138c8225

**Comment by blujan** [comment]
If I recall, the point of this was to consider a lack of trust at the application level (i.e., the software we are building) as opposed to just the database level (which we already ruled out for the time being).

So if the goal of this is so that the end user is the only one who has access to the data (thereby both the application and database have no knowledge), there is the problem that the end-user does not supply all of the data in this scheme. That is, incoming messages will still be handled by the server-side application we are building via the Twilio API. Moreover, these arrive in plain-text. In which case, there would still have to exist some level of trust for the application even if we were to encrypt it directly after receiving it.

**Comment by goldenapples** [comment]
> If I recall, the point of this was to consider a lack of trust at the application level (i.e., the software we are building) as opposed to just the database level (which we already ruled out for the time being).

That's correct. I had in mind a case where the threat model for the end user is _us_. For example, if we offer a hosted service, how could we alleviate any security concerns among the activist groups that would make up our end users about letting an unknown group of tech people have access to their membership database?

I had a vague idea  this might be possible with an architecture where the application doesn't interface with the database at all - all db querying happens on the client side, using a Firebase instance owned by the end user and the current user's Google authentication to query it. However, on talking it through, we realized we'd need a server-side process to make any API calls to Twilio (so as not to expose API keys to the client), so this seems not feasible, at least in the v1.0 product.

Also, for the initial build we'll be using a local database, so this is moot for now.

**Comment by blujan** [comment]
Close this for now, then?

**Comment by goldenapples** [comment]
Yeah, I'm in favor of closing this. If we come up with specific ideas to explore, we can open them as individual issues, but as it stands this is too undefined to do anything with.
